version: '3.7'

services:
  db:
    image: postgres:13.4
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    env_file: .env
    ports:
      - "8081:80"

volumes:
  postgres_data:
  pgadmin_data:
